### ISSUE TITLE
Create per-batch summary CSV and GCT files in the recipe

### ISSUE THREAD

**Issue by bethac07** [cytomining/profiling-recipe#17]
For the types and sizes of batches image analysts typically work with, these are the output files we rely on most at the end. Essentially, we just need all the per-plate files concatenated, and then pycytominer's write_gct applied. Could be done either always or as a step in the config (`summarize`? `stack`?)

**Comment by niranjchandrasekaran** [comment]
Completed in https://github.com/cytomining/profiling-recipe/pull/18
