### ISSUE TITLE
Include aggregation in recipe step

### ISSUE THREAD

**Issue by gwaygenomics** [cytomining/profiling-recipe#9]
Currently in the JUMP recipe, the first step in the image-based profiling pipeline (aggregation) is being performed by cytominer, instead of pycytominer. 

To streamline the recipe, the aggregation step should be ported to pycytominer.

Once cytomining/pycytominer#111 is merged, this step will be simple to port

**Comment by niranjchandrasekaran** [comment]
This has been completed.
